# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - pip install --use-mirrors codecov pytest-cov

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --use-mirrors mock nose

# command to run tests, e.g. python setup.py test
script:
  - py.test --cov=./

after_success:
  - codecov
